uni-meter {
  output = "uni-meter.output-devices.shelly-pro3em"

  input  = "uni-meter.input-devices.poweropti"

  output-devices {
    shelly-pro3em {
      udp-port = 1010

      min-sample-period = 5000ms
    }
  }

  input-devices {
    poweropti {
      url = "http://192.168.178.99"
      api-key = "abcdef12345678"

      # Provide the data from the Poweropti just on phase l1
      phase-mode = "mono-phase"
      power-phase = "l1"
    }
  }
}
